services:

  train0:
    build: docker/client
    ports:
      - 5000:5000
    environment:
      - TRAIN_PORT=5000
    command: python3 train_client.py
    volumes:
      - ../../02_data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
            memory: 7500M
    restart: always

  train1:
    build: docker/client
    ports:
      - 5001:5001
    environment:
      - TRAIN_PORT=5001
    command: python3 train_client.py
    volumes:
      - ../../02_data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
            memory: 7500M
    restart: always

  train2:
    build: docker/client
    ports:
      - 5002:5002
    environment:
      - TRAIN_PORT=5002
    command: python3 train_client.py
    volumes:
      - ../../02_data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
            memory: 7500M
    restart: always

  train3:
    build: docker/client
    ports:
      - 5003:5003
    environment:
      - TRAIN_PORT=5003
    command: python3 train_client.py
    volumes:
      - ../../02_data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
            memory: 7500M
    restart: always
              
  train4:
    build: docker/client
    ports:
      - 5004:5004
    environment:
      - TRAIN_PORT=5004
    command: python3 train_client.py
    volumes:
      - ../../02_data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
            memory: 7500M
    restart: always
              
  train5:
    build: docker/client
    ports:
      - 5005:5005
    environment:
      - TRAIN_PORT=5005
    command: python3 train_client.py
    volumes:
      - ../../02_data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
            memory: 7500M
    restart: always


  server:
    build: docker/server
    command: python3 train_server.py
    volumes:
      - ../../02_data/03_meeting_data:/meeting_data
      - ../../02_data:/data
      - ../../02_data/01_simulation_results:/simulation_results
      - ../../02_data/04_fl_performance:/results
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
